### ISSUE TITLE
Missing new chapter 9 moving to kubernetes content

### ISSUE THREAD

**Issue by gabema** [DanWahlin/Docker-for-Web-Developers#1]
Great pluralsite course!  I was curious to look at your sample project for the kubernetes generated files as well as the additional configuration for nginx and other services used in session 9 in pluralsite. Any plans to update this repo with those resources?

**Comment by DanWahlin** [comment]
Thanks! Glad you enjoyed the course. You can find the code for the last one in this repo:

https://github.com/DanWahlin/CodeWithDanDockerServices

**Comment by DanWahlin** [comment]
Thanks for asking by the way. Although I believe that the link is shown in the course, I've updated the project repository to show that module name and the readme has the details for the project I mentioned earlier.
